name: directory_picker
description: A flutter package to pick directories and handles requesting required permissions as well.
version: 1.0.0
author: Sundeep Babbur <sundeep.sundeep11@gmail.com>
homepage: https://github.com/DarkSouL11/flutter_directory_picker

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.6.2
  permission_handler: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
